name: Run E2E test

on:
  workflow_run:
    workflows:
      - "Deploy to Staging"
    types:
      - completed

jobs:
  run-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup E2E test
        run: npm ci
        working-directory: e2e

      - name: Run E2E test
        run: npm run test
        working-directory: e2e
        env:
          BASE_URL: https://fastify-webapp-sample-staging-b75a.up.railway.app
          HEADLESS: true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh_pages
          path: gh_pages

      - name: Generate Allure Report
        uses: allure-framework/allure-action@v1
        if: always()
        with:
          results_path: e2e/allure-results
          report_path: allure-report
          report_name: allure-report

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: allure-report
          keep_files: true